[rtx]
cache_dir = "~/.cache/rtx"
http_timeout = 5.0
http_retries = 2
osv_batch_size = 18
osv_max_concurrency = 4
disable_osv = false
github_max_concurrency = 6
gomod_metadata_concurrency = 5

policy_abandonment_threshold_days = 540
policy_churn_high_threshold = 10
policy_churn_medium_threshold = 5
policy_bus_factor_zero_threshold = 0
policy_bus_factor_one_threshold = 1
policy_low_maturity_threshold = 3
policy_typosquat_max_distance = 2
